version: '3'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/mydb"  # URI для подключения к MongoDB
    networks:
      - my_network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - my_network

networks:
  my_network:
